# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telacaduser.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_telacaduser(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setGeometry(QtCore.QRect(70, 50, 261, 130))
        self.frame.setMaximumSize(QtCore.QSize(300, 130))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.noFrame = QtWidgets.QFormLayout(self.frame)
        self.noFrame.setContentsMargins(0, 0, 0, 0)
        self.noFrame.setSpacing(0)
        self.noFrame.setObjectName("noFrame")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setMinimumSize(QtCore.QSize(40, 40))
        self.label_6.setStyleSheet("image: url(:/imagens/usuario.qrc.png);\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.noFrame.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(200, 35))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border: 3px solid rgb(86, 86 , 86);\n"
"    border-radius: 10px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:focus { \n"
"    border: 3px solid rgb(255, 255, 0);\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.noFrame.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setMinimumSize(QtCore.QSize(40, 40))
        self.label_7.setStyleSheet("\n"
"image: url(:/imagens/Senha.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.noFrame.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(200, 35))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border: 3px solid rgb(86, 86 , 86);\n"
"    border-radius: 10px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:focus { \n"
"    border: 3px solid rgb(255, 255, 0);\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.noFrame.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setStyleSheet("image: url(:/imagens/Senha.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.noFrame.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 35))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border: 3px solid rgb(86, 86 , 86);\n"
"    border-radius: 10px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:focus { \n"
"    border: 3px solid rgb(255, 255, 0);\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.noFrame.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(100, 190, 221, 40))
        self.frame_2.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(500, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.noFrame_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.noFrame_2.setContentsMargins(0, 0, 0, 0)
        self.noFrame_2.setSpacing(0)
        self.noFrame_2.setObjectName("noFrame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(80, 40))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(75, 75, 75);\n"
"    border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(75, 75, 75);\n"
"    border: 2px solid rgb(75, 75, 75);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(255, 234, 0);\n"
"    border: 2px solid rgb(255, 240, 69);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.noFrame_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(75, 75, 75);\n"
"    border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(75, 75, 75);\n"
"    border: 2px solid rgb(75, 75, 75);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(255, 234, 0);\n"
"    border: 2px solid rgb(255, 240, 69);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.noFrame_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Matrícula"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Senha"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Confirme a Senha"))
        self.pushButton.setText(_translate("Dialog", "Cadastrar"))
        self.pushButton_2.setText(_translate("Dialog", "Voltar"))
import IMAGENS.img
import IMAGENS.imagens

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())