# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telacadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_telacadastro(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(880, 516)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 891, 51))
        self.label.setStyleSheet("font: 75 16pt \"Arial\";\n"
"background-color: rgb(195, 195, 195);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 161, 31))
        self.label_2.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 100, 171, 16))
        self.label_3.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 120, 131, 31))
        self.label_4.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(360, 100, 161, 21))
        self.label_5.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(590, 70, 61, 16))
        self.label_7.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(360, 130, 131, 21))
        self.label_8.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(360, 70, 81, 21))
        self.label_9.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(160, 70, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 100, 161, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 130, 221, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(432, 70, 141, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(520, 100, 311, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(490, 130, 341, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(640, 70, 191, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 160, 891, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 220, 47, 13))
        self.label_10.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(10, 250, 71, 16))
        self.label_11.setStyleSheet("font: 75 12pt \"Arial\";\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(10, 280, 81, 16))
        self.label_12.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(430, 180, 161, 16))
        self.label_13.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(430, 210, 111, 16))
        self.label_14.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_14.setObjectName("label_14")
        self.lineEdit_8 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_8.setGeometry(QtCore.QRect(80, 190, 291, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_9.setGeometry(QtCore.QRect(80, 220, 291, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_10.setGeometry(QtCore.QRect(100, 280, 261, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 340, 901, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(410, 170, 20, 171))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEdit_11 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_11.setGeometry(QtCore.QRect(580, 180, 301, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_12.setGeometry(QtCore.QRect(540, 210, 231, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(20, 350, 101, 16))
        self.label_15.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(20, 390, 131, 16))
        self.label_16.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(20, 420, 111, 16))
        self.label_17.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(20, 480, 121, 21))
        self.label_18.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(20, 450, 161, 16))
        self.label_19.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_19.setObjectName("label_19")
        self.lineEdit_13 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_13.setGeometry(QtCore.QRect(140, 350, 131, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_14.setGeometry(QtCore.QRect(150, 390, 113, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_15.setGeometry(QtCore.QRect(140, 420, 121, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(320, 360, 151, 16))
        self.label_20.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(320, 390, 131, 16))
        self.label_21.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_21.setObjectName("label_21")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(0, 510, 901, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(280, 350, 20, 171))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(780, 360, 75, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: (60, 60, 60);\n"
"    border: 2px solid rgb(70, 70,70);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80);\n"
"    border: 2px solid rgb(100, 100 ,100);\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 255, 0);\n"
"    border: 2px solid rgb(238, 255, 78);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 460, 75, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: (60, 60, 60);\n"
"    border: 2px solid rgb(70, 70,70);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80);\n"
"    border: 2px solid rgb(100, 100 ,100);\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 255, 0);\n"
"    border: 2px solid rgb(238, 255, 78);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(700, 350, 20, 171))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(10, 0, 111, 51))
        self.label_22.setStyleSheet("image: url(:/cadastro/INSS.png);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(720, 10, 131, 41))
        self.label_23.setStyleSheet("image: url(:/Cadastrar.png);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(10, 0, 141, 51))
        self.label_24.setStyleSheet("image: url(:/Tela principal/INSS.png);")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(720, 0, 81, 51))
        self.label_25.setStyleSheet("image: url(:/Tela principal/Cadastrar.png);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(440, 240, 47, 13))
        self.label_26.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_26.setObjectName("label_26")
        self.lineEdit_16 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_16.setGeometry(QtCore.QRect(480, 240, 191, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(780, 410, 75, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: (60, 60, 60);\n"
"    border: 2px solid rgb(70, 70,70);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80);\n"
"    border: 2px solid rgb(100, 100 ,100);\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 255, 0);\n"
"    border: 2px solid rgb(238, 255, 78);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_17 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_17.setGeometry(QtCore.QRect(470, 360, 113, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_18.setGeometry(QtCore.QRect(450, 390, 113, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_19.setGeometry(QtCore.QRect(140, 450, 113, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_20.setGeometry(QtCore.QRect(140, 480, 113, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_21.setGeometry(QtCore.QRect(90, 250, 271, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(10, 310, 71, 16))
        self.label_27.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_27.setObjectName("label_27")
        self.lineEdit_22 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_22.setGeometry(QtCore.QRect(80, 310, 261, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 180, 51, 31))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: (60, 60, 60);\n"
"    border: 2px solid rgb(70, 70,70);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80);\n"
"    border: 2px solid rgb(100, 100 ,100);\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 255, 0);\n"
"    border: 2px solid rgb(238, 255, 78);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_23 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_23.setGeometry(QtCore.QRect(470, 460, 61, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(330, 450, 141, 31))
        self.label_28.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_28.setObjectName("label_28")
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setGeometry(QtCore.QRect(290, 430, 421, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setGeometry(QtCore.QRect(310, 470, 161, 31))
        self.label_29.setStyleSheet("font: 75 8pt \"Arial\";")
        self.label_29.setObjectName("label_29")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(-4, 50, 891, 481))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_7.raise_()
        self.line.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.lineEdit_8.raise_()
        self.lineEdit_9.raise_()
        self.lineEdit_10.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.lineEdit_11.raise_()
        self.lineEdit_12.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.lineEdit_13.raise_()
        self.lineEdit_14.raise_()
        self.lineEdit_15.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.line_6.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.lineEdit_16.raise_()
        self.pushButton_3.raise_()
        self.lineEdit_17.raise_()
        self.lineEdit_18.raise_()
        self.lineEdit_19.raise_()
        self.lineEdit_20.raise_()
        self.lineEdit_21.raise_()
        self.label_27.raise_()
        self.lineEdit_22.raise_()
        self.pushButton_4.raise_()
        self.lineEdit_23.raise_()
        self.label_28.raise_()
        self.line_7.raise_()
        self.label_29.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "                                                              CADASTRAR "))
        self.label_2.setText(_translate("Dialog", "Número do Beneficio :"))
        self.label_3.setText(_translate("Dialog", "Tipo de Acontecimento :"))
        self.label_4.setText(_translate("Dialog", "Fonte de Ação :"))
        self.label_5.setText(_translate("Dialog", "Número do Protocolo :"))
        self.label_7.setText(_translate("Dialog", "CPF :"))
        self.label_8.setText(_translate("Dialog", "Nome Segurado :"))
        self.label_9.setText(_translate("Dialog", "Espécie :"))
        self.label_10.setText(_translate("Dialog", "Rua :"))
        self.label_11.setText(_translate("Dialog", "Estado :"))
        self.label_12.setText(_translate("Dialog", "Municipio :"))
        self.label_13.setText(_translate("Dialog", "Nome Responsavel :"))
        self.label_14.setText(_translate("Dialog", "CPF  CNPJ :"))
        self.label_15.setText(_translate("Dialog", "Valor Dívida :"))
        self.label_16.setText(_translate("Dialog", "Valor Calculado : "))
        self.label_17.setText(_translate("Dialog", "Valor Entrada :"))
        self.label_18.setText(_translate("Dialog", "Parcels Pagas :"))
        self.label_19.setText(_translate("Dialog", "Total Parcelas :"))
        self.label_20.setText(_translate("Dialog", "Data da Cobrança :"))
        self.label_21.setText(_translate("Dialog", " Data do Calculo :"))
        self.pushButton.setText(_translate("Dialog", "Enviar"))
        self.pushButton_2.setText(_translate("Dialog", "Voltar"))
        self.label_26.setText(_translate("Dialog", "NIT :"))
        self.pushButton_3.setText(_translate("Dialog", "LIMPAR"))
        self.label_27.setText(_translate("Dialog", "Bairro :"))
        self.pushButton_4.setText(_translate("Dialog", "CEP"))
        self.label_28.setText(_translate("Dialog", "Ação Regressiva :"))
        self.label_29.setText(_translate("Dialog", "(RESPONDER SOMENTE sim/nao)"))
import IMAGENS.img
import IMAGENS.imagens


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Dialog = QtWidgets.QDialog()
        ui = Ui_telacadastro()
        ui.setupUi(Dialog)
        Dialog.show()
        sys.exit(app.exec_())
